import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#1b1b20',
        'primary-container': '#00f5ff',
        'surface-container-highest': '#35343a',
        'tertiary-fixed-dim': '#e7c427',
        'secondary': '#d7ffc5',
        'primary-fixed-dim': '#00dce5',
        'surface-container': '#1f1f25',
        'surface-variant': '#35343a',
        'on-tertiary-fixed-variant': '#544600',
        'outline': '#849495',
        'on-tertiary': '#3a3000',
        'tertiary-container': '#ffdb3f',
        'on-tertiary-fixed': '#221b00',
        'on-primary-fixed-variant': '#004f53',
        'on-primary': '#003739',
        'tertiary-fixed': '#ffe16c',
        'surface-bright': '#39383e',
        'primary-fixed': '#63f7ff',
        'on-secondary': '#053900',
        'surface-container-lowest': '#0e0e13',
        'surface': '#131318',
        'secondary-fixed': '#79ff5b',
        'surface-tint': '#00dce5',
        'on-primary-container': '#006c71',
        'on-secondary-container': '#0f6d00',
        'on-surface-variant': '#b9caca',
        'on-error': '#690005',
        'on-secondary-fixed': '#022100',
        'on-error-container': '#ffdad6',
        'secondary-fixed-dim': '#2ae500',
        'surface-container-high': '#2a292f',
        'on-primary-fixed': '#002021',
        'secondary-container': '#2ff801',
        'inverse-primary': '#00696e',
        'primary': '#e9feff',
        'surface-dim': '#131318',
        'outline-variant': '#3a494a',
        'on-tertiary-container': '#736000',
        'inverse-on-surface': '#303036',
        'error-container': '#93000a',
        'inverse-surface': '#e4e1e9',
        'background': '#0a0a0f',
        'on-background': '#e4e1e9',
        'on-surface': '#e4e1e9',
        'error': '#ffb4ab',
        'on-secondary-fixed-variant': '#095300',
        'tertiary': '#fff9f0',
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xl: '40px',
        gutter: '24px',
        sm: '8px',
        margin: '32px',
        xs: '4px',
        md: '16px',
        unit: '4px',
        xxl: '80px',
        lg: '24px',
      },
      fontFamily: {
        'headline-lg': ['Space Mono'],
        'label-sm': ['Space Mono'],
        'body-md': ['Sora'],
        'headline-lg-mobile': ['Space Mono'],
        'headline-md': ['Space Mono'],
        'body-lg': ['Sora'],
        'label-md': ['Space Mono'],
        'display-xl': ['Space Mono'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
        'display-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
} satisfies Config
